api_keys:
  api_key: QhTibgCwZjaDl01g37XpRKtro2qL7cgSunrXndfnazt9KZ0Nbcno0FPrV9Ja0hQ9
  secret: qDJAb8xpevCUjdUXrKr3XjmizCZDgNI0Oz8fkzN7qgyBqcGWrMoGLygL5iSxFhEz
capital_tbu: 220
symbols:
  leverage: 3
  max_open_positions: 2
  symbols:
  - BTCUSDT
  - ETHUSDT
  - XRPUSDT
  - SOLUSDT
  - ADAUSDT
  - BNBUSDT
  - SUIUSDT
  - DOTUSDT
  - HBARUSDT